---
- name: setup ec2 instances
  hosts: ec2-18-117-91-102.us-east-2.compute.amazonaws.com	
  tasks:
    - name: install Python3-pip
      apt:
        name: python3-pip
        state: present
        
