name: Ansible Deployment

on: 
  push:
  workflow_dispatch:
  
jobs:
  ansible-deploy:
    runs-on: ubuntu-lastest
    steps:
    - run: echo queloque
    - name: Authenticate to AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        
