name: Ansible Deployment

on: 
  push:
  workflow_dispatch:
  
jobs:
  ansible-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - name: Install Ansible (lastest)
      shell: pwsh
      run: | 
        pip3 install ansible boto3
    - name: Install Ansible Galaxy Collection (amazon.aws)
      shell: pwsh
      run: |
        ansible-galaxy collection install amazon.aws
    - name: Authenticate to AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Validate Ansible Inventory
      shell: pwsh
      run: | 
        ansible-inventory --inventory inventory.aws_ec2.yml --list
    - name: Run Ansible Playbook
      shell: pwsh
      run: |
        ansible-playbook --inventory inventory.aws_ec2.yml playbook.yml
    
        
